server:
  port: 80

spring:
  profiles:
    active: dev

wechat:
  appId: XXXXXX
  secret: XXXXXXXXXXXXX
  redirectUrl: http://www.XXXX.com  #微信网页授权配置 回调域名

logging:
  level.root: info
  level.web.page.authorization: debug
  file: G:/mylog/authorization.log